llm:
  MODEL: qwen2.5-coder:32b
  TEMPERATURE: 0.1
  TOP_K: 20
  TOP_P: 0.8
  SEED: 42
  TIMEOUT_SECONDS: 900
  LLM_ENDPOINT: http://localhost:11434/api/generate
  REPEAT_PENALTY: 1.05
  REPEAT_LAST_N: 128
  NUM_PREDICT: 900

rag:
  ENABLED: True
  RAG_N: 2

runner:
  MAX_REPAIR_ITERATIONS: 6
  TIMEOUT: 10

store:
  DB_NAME: dissertation