llm:
  MODEL: qwen2.5-coder:32b
  TEMPERATURE: 0.2
  TOP_K: 50
  TOP_P: 0.8
  SEED: 42
  TIMEOUT_SECONDS: 900
  LLM_ENDPOINT: http://localhost:11434/api/generate

rag:
  ENABLED: True
  RAG_N: 3

runner:
  MAX_REPAIR_ITERATIONS: 6
  TIMEOUT: 10

store:
  DB_NAME: dissertation